name: ci

on: [push, pull_request]

jobs:

  core:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.x']

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install .[tests,lint]

    - name: "install GCC (macos)"
      if: runner.os == 'macOS'
      run: brew reinstall gcc

    - run: flake8
    - run: mypy

    - run: pytest
